### PR TITLE
Add link to docker-compose-project

### PR DESCRIPTION
**Pull request by throbbingcat**
Maybe you want to include a link to my docker-compose-project. Thanks for this tool anyway!

Best regards

### CODE REVIEW

**Comment by orangecoding** [comment]
@throbbingcat thanks for this. Wouldn't it make more sense to merge your changes to this repo? Can you create a pr including the docker changes?

**Comment by throbbingcat** [comment]
I probably could, but not at the moment. Maybe in the next weeks I can try.

**Comment by orangecoding** [comment]
@throbbingcat if you are ok with that, I could also take the changes and do it by myself, tagging in the readme, that this changes are done by you...

**Comment by throbbingcat** [comment]
Sure, go for it.

**Comment by orangecoding** [comment]
done. Thanks!

**Pull request closed without merging**
